// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwtvKeiChbBfKmsQgqu6wzfXs51YYhIW0',
    appId: '1:566599100108:web:f8ecd14f40a068eb168469',
    messagingSenderId: '566599100108',
    projectId: 'ubcab-app',
    authDomain: 'ubcab-app.firebaseapp.com',
    storageBucket: 'ubcab-app.firebasestorage.app',
    measurementId: 'G-J68M8J6RVC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT1NJrVOaj_zKzC0FYa1r_oohLKms0_84',
    appId: '1:566599100108:android:e61aa5b3febaec2d168469',
    messagingSenderId: '566599100108',
    projectId: 'ubcab-app',
    storageBucket: 'ubcab-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8TwkclSO2h18PbLrjwDauq_pTSb0wGRQ',
    appId: '1:566599100108:ios:6432d9e2b99ae637168469',
    messagingSenderId: '566599100108',
    projectId: 'ubcab-app',
    storageBucket: 'ubcab-app.firebasestorage.app',
    iosBundleId: 'com.example.riderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8TwkclSO2h18PbLrjwDauq_pTSb0wGRQ',
    appId: '1:566599100108:ios:6432d9e2b99ae637168469',
    messagingSenderId: '566599100108',
    projectId: 'ubcab-app',
    storageBucket: 'ubcab-app.firebasestorage.app',
    iosBundleId: 'com.example.riderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwtvKeiChbBfKmsQgqu6wzfXs51YYhIW0',
    appId: '1:566599100108:web:3117ee8dac3b5027168469',
    messagingSenderId: '566599100108',
    projectId: 'ubcab-app',
    authDomain: 'ubcab-app.firebaseapp.com',
    storageBucket: 'ubcab-app.firebasestorage.app',
    measurementId: 'G-Z8EP6QP11Z',
  );
}
